#!/bin/bash

# command-line invocations to generate grid files used in ../test_stitch.py
# (tiles used in these operations previously generated by
# ./fringe_and_stitch_tiles.sh)


# 1x1 tile tests:

# join the eastern edge of tile A with the western edge of tile B:
sgstitch                                \
  --tilea tile_A_1x1.mitgrid            \
  --nia 1                               \
  --nja 1                               \
  --tileb tile_B_E_1x1.mitgrid          \
  --nib 1                               \
  --njb 1                               \
  --outfile stitch_AB_EW_2x1.mitgrid

# join the northern edge of tile A with the southern edge of tile B:
sgstitch                                \
  --tilea tile_A_1x1.mitgrid            \
  --nia 1                               \
  --nja 1                               \
  --tileb tile_B_N_1x1.mitgrid          \
  --nib 1                               \
  --njb 1                               \
  --outfile stitch_AB_NS_1x2.mitgrid

# join the western edge of tile A with the eastern edge of tile B:
sgstitch                                \
  --tilea tile_A_1x1.mitgrid            \
  --nia 1                               \
  --nja 1                               \
  --tileb tile_B_W_1x1.mitgrid          \
  --nib 1                               \
  --njb 1                               \
  --outfile stitch_AB_WE_2x1.mitgrid

# join the southern edge of tile A with the northern edge of tile B:
sgstitch                                \
  --tilea tile_A_1x1.mitgrid            \
  --nia 1                               \
  --nja 1                               \
  --tileb tile_B_S_1x1.mitgrid          \
  --nib 1                               \
  --njb 1                               \
  --outfile stitch_AB_SN_1x2.mitgrid


# 2x2 tile tests:

# join the eastern edge of tile A with the western edge of tile B:
sgstitch                                \
  --tilea tile_A_2x2.mitgrid            \
  --nia 2                               \
  --nja 2                               \
  --tileb tile_B_E_2x2.mitgrid          \
  --nib 2                               \
  --njb 2                               \
  --outfile stitch_AB_EW_4x2.mitgrid

# join the northern edge of tile A with the southern edge of tile B:
sgstitch                                \
  --tilea tile_A_2x2.mitgrid            \
  --nia 2                               \
  --nja 2                               \
  --tileb tile_B_N_2x2.mitgrid          \
  --nib 2                               \
  --njb 2                               \
  --outfile stitch_AB_NS_2x4.mitgrid

# join the western edge of tile A with the eastern edge of tile B:
sgstitch                                \
  --tilea tile_A_2x2.mitgrid            \
  --nia 2                               \
  --nja 2                               \
  --tileb tile_B_W_2x2.mitgrid          \
  --nib 2                               \
  --njb 2                               \
  --outfile stitch_AB_WE_4x2.mitgrid

# join the southern edge of tile A with the northern edge of tile B:
sgstitch                                \
  --tilea tile_A_2x2.mitgrid            \
  --nia 2                               \
  --nja 2                               \
  --tileb tile_B_S_2x2.mitgrid          \
  --nib 2                               \
  --njb 2                               \
  --outfile stitch_AB_SN_2x4.mitgrid

